//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblQuestion()
        {
            this.TblUserAnswers = new HashSet<TblUserAnswer>();
        }
    
        public int QueId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public string Question { get; set; }
        public string ControlType { get; set; }
        public string ControlOptions { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserAnswer> TblUserAnswers { get; set; }
        public virtual TblSurvey TblSurvey { get; set; }
    }
}
