//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserAnswer
    {
        public int AnswerId { get; set; }
        public string UserAnswer { get; set; }
        public int UserId { get; set; }
        public int QuesId { get; set; }
    
        public virtual TblQuestion TblQuestion { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
